<?xml version="1.0"?>
<VaisResource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.geaviation.com/vais/config">
  <ResourceVersionInfo SchemaVersion="2" FileVersion="264" VaisToolName="ConfigEditor" VaisToolVersion="558.171.0.0" />
  <ComputingResource ComputingResourceName="DefaultNode" Description="DefaultNode" MachineName="DefaultNode" CoreCount="2" MemoryGB="4">
    <ResourceUtilityAllocation UtilityName="DiscreteControllerGUIParticipant" />
    <ResourceUtilityAllocation UtilityName="DiscreteControllerModelParticipant" />
    <ResourceUtilityAllocation UtilityName="DiscreteIOGateway" />
  </ComputingResource>
</VaisResource>