#ifndef GPIADISCRETE
#define GPIADISCRETE

#include "Common\DeviceProcedure.h"

#ifndef GPIADISCRETE_DEVICETEST_NUMBER
#define GPIADISCRETE_DEVICETEST_NUMBER 3
#endif
#ifndef BIT_TEST_NUMBER
#define BIT_TEST_NUMBER 2
#endif

#ifndef DISCRETE_PORT_BANK_NUMBER_MAX
#define DISCRETE_PORT_BANK_NUMBER_MAX 4
#endif

#ifndef GPIADISCRETE_BITSBANK_NUMBER_MAX
#define GPIADISCRETE_BITSBANK_NUMBER_MAX 4
#endif
#ifndef GPIADISCRETE_BITSBANK_BITS_MAX
#define GPIADISCRETE_BITSBANK_BITS_MAX 8
#endif

#endif